"""empty message

Revision ID: ce0e6f1df18e
Revises: c48a1366d3ca
Create Date: 2019-11-20 13:16:01.772414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce0e6f1df18e'
down_revision = 'c48a1366d3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('group', 'group_name',
               existing_type=mysql.VARCHAR(charset='utf8', length=20),
               nullable=False)
    op.alter_column('plate', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', length=20),
               nullable=False)
    op.alter_column('topic', 'title',
               existing_type=mysql.VARCHAR(charset='utf8', length=20),
               nullable=False)
    op.add_column('user', sa.Column('password', sa.String(length=128), nullable=False))
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', length=20),
               nullable=True)
    op.drop_column('user', 'password')
    op.alter_column('topic', 'title',
               existing_type=mysql.VARCHAR(charset='utf8', length=20),
               nullable=True)
    op.alter_column('plate', 'name',
               existing_type=mysql.VARCHAR(charset='utf8', length=20),
               nullable=True)
    op.alter_column('group', 'group_name',
               existing_type=mysql.VARCHAR(charset='utf8', length=20),
               nullable=True)
    # ### end Alembic commands ###
